# ADITYA BIRLA SUN LIFE SCRAPER CONFIGURATION
# ==========================================

amc_name: "ABSLF"
full_name: "Aditya Birla Sun Life Asset Management Company Limited"
website: "https://mutualfund.adityabirlacapital.com"
active: true

# Base URL patterns for different disclosure types
url_patterns:
  monthly_portfolio: "https://mutualfund.adityabirlacapital.com/-/media/bsl/files/resources/monthly-portfolio/{year}/sebi_monthly_portfolio-{date}-{year}.zip"
  fortnightly_portfolio: "https://mutualfund.adityabirlacapital.com/-/media/bsl/files/resources/fortnightly-portfolio/{year}/sebi_fortnightly_portfolio_{date}-{year}.zip"

# Disclosure types configuration
disclosure_types:
  monthly:
    pattern_key: "monthly_portfolio"
    frequency: "monthly"
    date_patterns:
      - "31-january"
      - "28-february" 
      - "31-march"
      - "30-april"
      - "31-may"
      - "30-june"
      - "31-july"
      - "31-august"
      - "30-september"
      - "31-october"
      - "30-november"
      - "31-december"
    
  fortnightly:
    pattern_key: "fortnightly_portfolio" 
    frequency: "fortnightly"
    date_patterns:
      # First half of month (15th)
      - "15-jan"
      - "15-feb"
      - "15-mar"
      - "15-apr"
      - "15-may"
      - "15-jun"
      - "15-jul"
      - "15-aug"
      - "15-sep"
      - "15-oct"
      - "15-nov"
      - "15-dec"
      # End of month (last day)
      - "31-jan"
      - "28-feb"
      - "31-mar" 
      - "30-apr"
      - "31-may"
      - "30-jun"
      - "31-jul"
      - "31-aug"
      - "30-sep"
      - "31-oct"
      - "30-nov"
      - "31-dec"

# Output configuration
output:
  base_dir: "data/raw"
  folder_structure: "{date}/{amc_name}"
  
# Request settings
request_settings:
  user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"
  timeout: 30
  delay_between_requests: 2
  max_retries: 3

# Years to check (current and previous year by default)
years_to_check: 2